name: Fly Deploy Staging

on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to Staging
        runs-on: ubuntu-latest
        concurrency: deploy-staging-group
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Deploy to Staging
              run: flyctl deploy --remote-only --config fly.staging.toml --build-arg SITE_URL=https://staging.fraugsleeves.dev
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_TOKEN }}
